name: Generate 3D Gradient Snake

on:
  workflow_dispatch:   # run manually from Actions tab
  schedule:
    - cron: '0 0 * * *'   # runs daily at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate 3D Gradient Snake
        uses: Platane/snk@v3
        with:
          github_user_name: dipanshubatra
          outputs: dist/snake.svg
          shape: cube        # makes it 3D blocks
          theme: gradient    # rainbow gradient colors

      - name: Commit and push to output branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Switch to output branch (create if doesn't exist)
          if git ls-remote --exit-code --heads origin output; then
            git checkout output
            git rm -rf .
          else
            git checkout --orphan output
            git reset --hard
          fi

          # Copy generated snake.svg
          cp -r dist/* .

          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update 3D gradient snake [skip ci]"
            git push origin output --force
          fi
